// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iyodrriwogmsdwrlwjsg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml5b2Rycml3b2dtc2R3cmx3anNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0MDU0NzksImV4cCI6MjA2Nzk4MTQ3OX0.bKQwshnsTYzPreAiL3w3efunnGWpjYenb4QOBHuiN2Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});